[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "AssertMixins"
description = "Library of testing helper mixins."
authors = [
	{ name = "João Jerónimo", email = "joao.jeronimo.pro@gmail.com" }
	]
classifiers = [
	"Development Status :: 5 - Production/Stable",
	]
version="0.1.0"
dependencies = [
	]
requires-python = ">=3.7"
